### ISSUE TITLE
Looking for the same example in pure ObjC

### ISSUE THREAD

**Issue by ArkadiYoskovitz** [mattneub/custom-alert-view-iOS7#4]
Hi,

Looked at the code and looks interesting and useful for a project I'm working on but i need it in objC only. Due to constraints with my projects.

Can you add a branch with objC only code? or tell me where i can find it?

**Comment by mattneub** [comment]
Commits prior to 71e3d3f were in Objective-C.

**Comment by ArkadiYoskovitz** [comment]
Thank you for the help
